[tool.poetry]
name = "app"
version = "0.1.0"
description = ""
authors = [
    "James Hodgkinson <james@terminaloutcomes.com>",
]

[tool.poetry.dependencies]
python = "^3.9"
pydantic = "^1.10.5"
schedule = "^1.1.0"

[tool.poetry.dependencies.pyaussiebb]
git = "https://github.com/yaleman/pyaussiebb"
rev = "outages"

[tool.poetry.dev-dependencies]
pylint = "^2.16.1"
pytest = "^7.2.1"
black = "^23.1.0"
mypy = "^1.0"
pylint-pydantic = "^0.1.6"

[build-system]
requires = [
    "poetry-core>=1.0.0",
]
build-backend = "poetry.core.masonry.api"

[project]
name = "app"
version = "0.1.0"
authors = [
    { name = "James Hodgkinson", email = "james@terminaloutcomes.com" },
]
description = "silly container thing"
