[tool.poetry]
name = "app"
version = "0.1.0"
description = ""
authors = ["James Hodgkinson <james@terminaloutcomes.com>"]

[tool.poetry.dependencies]
python = "^3.10"
pydantic = "^2.5.3"
schedule = "^1.2.1"
pyaussiebb = "0.1.3"

[tool.poetry.group.dev.dependencies]
ruff = "^0.1.9"
mypy = "^1.8.0"
black = "^23.12.0"
pytest = "^7.4.3"
pylint-pydantic = "^0.3.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[project]
name = "app"
version = "0.1.0"
authors = [{ name = "James Hodgkinson", email = "james@terminaloutcomes.com" }]
description = "silly container thing"

[tool.ruff]
line-length = 200
