[tool.poetry]
name = "app"
version = "0.1.0"
description = ""
authors = ["James Hodgkinson <james@terminaloutcomes.com>"]

[tool.poetry.dependencies]
python = "^3.10"
pydantic = "^2.4.2"
schedule = "^1.2.1"
pyaussiebb = "0.1.3"

[tool.poetry.group.dev.dependencies]
ruff = "^0.1.1"
mypy = "^1.6.1"
black = "^23.9.1"
pytest = "^7.4.2"
pylint-pydantic = "^0.3.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[project]
name = "app"
version = "0.1.0"
authors = [{ name = "James Hodgkinson", email = "james@terminaloutcomes.com" }]
description = "silly container thing"

[tool.ruff]
line-length = 200
